version: '3.5'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8005:80"
    volumes:
      - ./docker/nginx/hosts-local:/etc/nginx/conf.d
      - ./:/var/www
      - ./logs/nginx/:/var/log/nginx:cached
    depends_on:
      - laravel-api

  laravel-api:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      args:
        - USER_ID
        - GROUP_ID
    container_name: laravel-api
    volumes:
      - ./:/var/www
      - ./data/composer:/.composer
      - ./logs/laravel:/var/www/var/logs:cached
    environment:
        XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST} client_port=${XDEBUG_CLIENT_PORT}
        PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    depends_on:
      - mysql
      - redis

  mysql:
    build:
        context: ./docker/mysql
        dockerfile: ./Dockerfile
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: dbpass
        MYSQL_DATABASE: laravel_db
    ports:
        - "3309:3306"
    volumes:
        - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "6379:6379/udp"
    environment:
      REDIS_PASSWORD: redisroot
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "redisroot"]
